trigger:
  - master

stages:
  - stage: Copy
    displayName: COPY ARM template to staging
    jobs:
     - job: Copy
       displayName: COPY
       pool:
        vmImage: 'ubuntu-16.04'
       steps:
         - task: CopyFiles@2
           inputs:
             SourceFolder: $(Build.SourcesDirectory)/ARMTemplates
             TargetFolder: $(Build.ArtifactStagingDirectory)
             CleanTargetFolder: true

  - stage: Deploy
    displayName: Deploy ARM template
    jobs:
      - job: Deploy
        displayName: Deploy
        pool:
          vmImage: 'ubuntu-16.04'
        steps:
          - task: AzureResourceGroupDeployment@2
            inputs:
              azureSubscription: ARMServiceConnection
              action: Create Or Update Resource Group
              deploymentMode: Complete
              resourceGroupName: Multi
              templateLocation: Linked artifact              